"""update table users

Revision ID: 4b875a971d57
Revises: 2007bb5f7eda
Create Date: 2024-07-18 23:42:11.719340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b875a971d57"
down_revision: Union[str, None] = "2007bb5f7eda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_foo", "users", type_="unique")
    op.create_unique_constraint(
        op.f("uq_users_foo_bar"), "users", ["foo", "bar"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_foo_bar"), "users", type_="unique")
    op.create_unique_constraint("uq_users_foo", "users", ["foo", "bar"])
    # ### end Alembic commands ###
